# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_messages_v1.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common_messages_v1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63ommon_messages_v1.proto\x12\x13\x63oherence.common.v1\x1a\x19google/protobuf/any.proto\"=\n\x0c\x45rrorMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\x05\x65rror\x18\x02 \x01(\x0cH\x00\x88\x01\x01\x42\x08\n\x06_error\"\n\n\x08\x43omplete\";\n\x10HeartbeatMessage\x12\x11\n\x04uuid\x18\x01 \x01(\x0cH\x00\x88\x01\x01\x12\x0b\n\x03\x61\x63k\x18\x02 \x01(\x08\x42\x07\n\x05_uuid\"/\n\rOptionalValue\x12\x0f\n\x07present\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\")\n\x17\x43ollectionOfBytesValues\x12\x0e\n\x06values\x18\x01 \x03(\x0c\"/\n\x11\x42inaryKeyAndValue\x12\x0b\n\x03key\x18\x01 \x01(\x0c\x12\r\n\x05value\x18\x02 \x01(\x0c\"*\n\x18\x43ollectionOfStringValues\x12\x0e\n\x06values\x18\x01 \x03(\t\"#\n\x11\x43ollectionOfInt32\x12\x0e\n\x06values\x18\x01 \x03(\x05\"#\n\x11\x43ollectionOfInt64\x12\x0e\n\x06values\x18\x01 \x03(\x03\x42\x30\n,com.oracle.coherence.grpc.messages.common.v1P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_messages_v1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.oracle.coherence.grpc.messages.common.v1P\001'
  _globals['_ERRORMESSAGE']._serialized_start=76
  _globals['_ERRORMESSAGE']._serialized_end=137
  _globals['_COMPLETE']._serialized_start=139
  _globals['_COMPLETE']._serialized_end=149
  _globals['_HEARTBEATMESSAGE']._serialized_start=151
  _globals['_HEARTBEATMESSAGE']._serialized_end=210
  _globals['_OPTIONALVALUE']._serialized_start=212
  _globals['_OPTIONALVALUE']._serialized_end=259
  _globals['_COLLECTIONOFBYTESVALUES']._serialized_start=261
  _globals['_COLLECTIONOFBYTESVALUES']._serialized_end=302
  _globals['_BINARYKEYANDVALUE']._serialized_start=304
  _globals['_BINARYKEYANDVALUE']._serialized_end=351
  _globals['_COLLECTIONOFSTRINGVALUES']._serialized_start=353
  _globals['_COLLECTIONOFSTRINGVALUES']._serialized_end=395
  _globals['_COLLECTIONOFINT32']._serialized_start=397
  _globals['_COLLECTIONOFINT32']._serialized_end=432
  _globals['_COLLECTIONOFINT64']._serialized_start=434
  _globals['_COLLECTIONOFINT64']._serialized_end=469
# @@protoc_insertion_point(module_scope)
