# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proxy_service_v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import coherence.proxy_service_messages_v1_pb2 as proxy__service__messages__v1__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proxy_service_v1.proto\x12\x12\x63oherence.proxy.v1\x1a\x1fproxy_service_messages_v1.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto2g\n\x0cProxyService\x12W\n\nsubChannel\x12 .coherence.proxy.v1.ProxyRequest\x1a!.coherence.proxy.v1.ProxyResponse\"\x00(\x01\x30\x01\x42/\n+com.oracle.coherence.grpc.services.proxy.v1P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proxy_service_v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n+com.oracle.coherence.grpc.services.proxy.v1P\001'
  _PROXYSERVICE._serialized_start=140
  _PROXYSERVICE._serialized_end=243
# @@protoc_insertion_point(module_scope)
